### ISSUE TITLE
зачем переменная sum_word?

### ISSUE THREAD

**Issue by DanaZL** [AZuev1986/lp_lesson3#1]
https://github.com/AZuev1986/lp_lesson3/blob/86295c9e3a11c6417747a3a380593612602ffc7d/file.py#L6

Зачем переменная sum_word, еще и (проинициализированная 2 раза:) ), если можно сразу считать весь файл?

**Comment by AntZuev** [comment]
Счетчик слов. 2 раза, чтобы наверняка) Не стал файл целиком считывать, потому что мне показалось что при построчном считывании проще учесть встречающиеся  символы перевода строки '\n', иначе можно получить напрмер такие слова  "год.\n\nОднакo" и количество слов тогда некорректным будет

**Comment by DanaZL** [comment]
split() делит по всем продельным символам, включая перенос строки :)

**Comment by AntZuev** [comment]
исправил
